module.exports = [
  { "name": "Product A", "description": "Description of Product A", "url": "http://example.com/product-a" },
  { "name": "Product B", "description": "Description of Product B", "url": "http://example.com/product-b" },
  { "name": "Product C", "description": "Description of Product C", "url": "http://example.com/product-c" },
  { "name": "Product D", "description": "Description of Product D", "url": "http://example.com/product-d" },
  { "name": "Product E", "description": "Description of Product E", "url": "http://example.com/product-e" },
  { "name": "Product F", "description": "Description of Product F", "url": "http://example.com/product-f" },
  { "name": "Product G", "description": "Description of Product G", "url": "http://example.com/product-g" },
  { "name": "Product H", "description": "Description of Product H", "url": "http://example.com/product-h" },
  { "name": "Product I", "description": "Description of Product I", "url": "http://example.com/product-i" },
  { "name": "Product J", "description": "Description of Product J", "url": "http://example.com/product-j" },
  { "name": "Product K", "description": "Description of Product K", "url": "http://example.com/product-k" },
  { "name": "Product L", "description": "Description of Product L", "url": "http://example.com/product-l" },
  { "name": "Product M", "description": "Description of Product M", "url": "http://example.com/product-m" },
  { "name": "Product N", "description": "Description of Product N", "url": "http://example.com/product-n" },
  { "name": "Product O", "description": "Description of Product O", "url": "http://example.com/product-o" },
  { "name": "Product P", "description": "Description of Product P", "url": "http://example.com/product-p" },
  { "name": "Product Q", "description": "Description of Product Q", "url": "http://example.com/product-q" },
  { "name": "Product R", "description": "Description of Product R", "url": "http://example.com/product-r" },
  { "name": "Product S", "description": "Description of Product S", "url": "http://example.com/product-s" },
  { "name": "Product T", "description": "Description of Product T", "url": "http://example.com/product-t" }
]
